// Code generated by MockGen. DO NOT EDIT.
// Source: supply.go

// Package supply_test is a generated GoMock package.
package supply_test

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStager is a mock of Stager interface
type MockStager struct {
	ctrl     *gomock.Controller
	recorder *MockStagerMockRecorder
}

// MockStagerMockRecorder is the mock recorder for MockStager
type MockStagerMockRecorder struct {
	mock *MockStager
}

// NewMockStager creates a new mock instance
func NewMockStager(ctrl *gomock.Controller) *MockStager {
	mock := &MockStager{ctrl: ctrl}
	mock.recorder = &MockStagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStager) EXPECT() *MockStagerMockRecorder {
	return m.recorder
}

// LinkDirectoryInDepDir mocks base method
func (m *MockStager) LinkDirectoryInDepDir(arg0, arg1 string) error {
	ret := m.ctrl.Call(m, "LinkDirectoryInDepDir", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkDirectoryInDepDir indicates an expected call of LinkDirectoryInDepDir
func (mr *MockStagerMockRecorder) LinkDirectoryInDepDir(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkDirectoryInDepDir", reflect.TypeOf((*MockStager)(nil).LinkDirectoryInDepDir), arg0, arg1)
}

// DepDir mocks base method
func (m *MockStager) DepDir() string {
	ret := m.ctrl.Call(m, "DepDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// DepDir indicates an expected call of DepDir
func (mr *MockStagerMockRecorder) DepDir() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepDir", reflect.TypeOf((*MockStager)(nil).DepDir))
}

// CacheDir mocks base method
func (m *MockStager) CacheDir() string {
	ret := m.ctrl.Call(m, "CacheDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// CacheDir indicates an expected call of CacheDir
func (mr *MockStagerMockRecorder) CacheDir() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheDir", reflect.TypeOf((*MockStager)(nil).CacheDir))
}

// MockApt is a mock of Apt interface
type MockApt struct {
	ctrl     *gomock.Controller
	recorder *MockAptMockRecorder
}

// MockAptMockRecorder is the mock recorder for MockApt
type MockAptMockRecorder struct {
	mock *MockApt
}

// NewMockApt creates a new mock instance
func NewMockApt(ctrl *gomock.Controller) *MockApt {
	mock := &MockApt{ctrl: ctrl}
	mock.recorder = &MockAptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApt) EXPECT() *MockAptMockRecorder {
	return m.recorder
}

// Setup mocks base method
func (m *MockApt) Setup() error {
	ret := m.ctrl.Call(m, "Setup")
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup
func (mr *MockAptMockRecorder) Setup() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockApt)(nil).Setup))
}

// HasKeys mocks base method
func (m *MockApt) HasKeys() bool {
	ret := m.ctrl.Call(m, "HasKeys")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasKeys indicates an expected call of HasKeys
func (mr *MockAptMockRecorder) HasKeys() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasKeys", reflect.TypeOf((*MockApt)(nil).HasKeys))
}

// HasRepos mocks base method
func (m *MockApt) HasRepos() bool {
	ret := m.ctrl.Call(m, "HasRepos")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasRepos indicates an expected call of HasRepos
func (mr *MockAptMockRecorder) HasRepos() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRepos", reflect.TypeOf((*MockApt)(nil).HasRepos))
}

// AddKeys mocks base method
func (m *MockApt) AddKeys() (string, error) {
	ret := m.ctrl.Call(m, "AddKeys")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKeys indicates an expected call of AddKeys
func (mr *MockAptMockRecorder) AddKeys() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKeys", reflect.TypeOf((*MockApt)(nil).AddKeys))
}

// AddRepos mocks base method
func (m *MockApt) AddRepos() error {
	ret := m.ctrl.Call(m, "AddRepos")
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRepos indicates an expected call of AddRepos
func (mr *MockAptMockRecorder) AddRepos() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRepos", reflect.TypeOf((*MockApt)(nil).AddRepos))
}

// Update mocks base method
func (m *MockApt) Update() (string, error) {
	ret := m.ctrl.Call(m, "Update")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockAptMockRecorder) Update() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApt)(nil).Update))
}

// Download mocks base method
func (m *MockApt) Download() (string, error) {
	ret := m.ctrl.Call(m, "Download")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download
func (mr *MockAptMockRecorder) Download() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockApt)(nil).Download))
}

// Install mocks base method
func (m *MockApt) Install() (string, error) {
	ret := m.ctrl.Call(m, "Install")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install
func (mr *MockAptMockRecorder) Install() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockApt)(nil).Install))
}
